In [ ]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib as plt
%matplotlib inline

In [3]:
df = pd.read_csv(r"C:\Users\skaur\Downloads\Heart Disease Prediction\data\HeartDiseaseTrain-Test.csv")
df.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            1025 non-null   int64
 1   sex                            1025 non-null   str
 2   chest_pain_type                1025 non-null   str
 3   resting_blood_pressure         1025 non-null   int64
 4   cholestoral                    1025 non-null   int64
 5   fasting_blood_sugar            1025 non-null   str
 6   rest_ecg                       1025 non-null   str
 7   Max_heart_rate                 1025 non-null   int64
 8   exercise_induced_angina        1025 non-null   str
 9   oldpeak                        1025 non-null   float64
 10  slope                          1025 non-null   str
 11  vessels_colored_by_flourosopy  1025 non-null   str
 12  thalassemia                    1025 non-null   str
 13  target                         1025 non-null   int64
dtypes: float64(1), int64(5), str(8)
memory usage: 192.8 KB

In [6]:
df.shape

(1025, 14)

In [7]:
df.isnull().sum()

age                              0
sex                              0
chest_pain_type                  0
resting_blood_pressure           0
cholestoral                      0
fasting_blood_sugar              0
rest_ecg                         0
Max_heart_rate                   0
exercise_induced_angina          0
oldpeak                          0
slope                            0
vessels_colored_by_flourosopy    0
thalassemia                      0
target                           0
dtype: int64

**NO Nulls**

In [11]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.drop_duplicates(inplace=True)

In [17]:
df.shape

(302, 14)

In [12]:
df.describe()

,age,resting_blood_pressure,cholestoral,Max_heart_rate,oldpeak,target
count,302.00000,302.000000,302.000000,302.000000,302.000000,302.000000
mean,54.42053,131.602649,246.500000,149.569536,1.043046,0.543046
std,9.04797,17.563394,51.753489,22.903527,1.161452,0.498970
min,29.00000,94.000000,126.000000,71.000000,0.000000,0.000000
25%,48.00000,120.000000,211.000000,133.250000,0.000000,0.000000
50%,55.50000,130.000000,240.500000,152.500000,0.800000,1.000000
75%,61.00000,140.000000,274.750000,166.000000,1.600000,1.000000
max,77.00000,200.000000,564.000000,202.000000,6.200000,1.000000

### Check the values of categorical columns

In [14]:
df['chest_pain_type'].value_counts()

chest_pain_type
Typical angina      143
Non-anginal pain     86
Atypical angina      50
Asymptomatic         23
Name: count, dtype: int64

In [15]:
df['sex'].value_counts()

sex
Male      206
Female     96
Name: count, dtype: int64

In [16]:
df['fasting_blood_sugar'].value_counts()

fasting_blood_sugar
Lower than 120 mg/ml      257
Greater than 120 mg/ml     45
Name: count, dtype: int64

In [18]:
df['rest_ecg'].value_counts()

rest_ecg
ST-T wave abnormality           151
Normal                          147
Left ventricular hypertrophy      4
Name: count, dtype: int64

In [19]:
df['exercise_induced_angina'].value_counts()

exercise_induced_angina
No     203
Yes     99
Name: count, dtype: int64

In [20]:
df['vessels_colored_by_flourosopy'].value_counts()

vessels_colored_by_flourosopy
Zero     175
One       65
Two       38
Three     20
Four       4
Name: count, dtype: int64

In [21]:
df['thalassemia'].value_counts()

thalassemia
Fixed Defect         165
Reversable Defect    117
Normal                18
No                     2
Name: count, dtype: int64

In [22]:
df['slope'].value_counts()

slope
Downsloping    141
Flat           140
Upsloping       21
Name: count, dtype: int64

In [23]:
df['target'].value_counts()

target
1    164
0    138
Name: count, dtype: int64

In [29]:
df.to_csv('../data/heart_cleaned.csv', index=False)